import random
from celery import shared_task
from django.db import transaction
from .models import Category, Product

WORDS=["Alpha","Bravo","Delta","Echo","Foxtrot","Gamma","Zeta","Omega","Sigma","Charlie"]

def create_dummy_products(category_id:int, n:int=1000):
    cat=Category.get(pk=category_id)
    batch=[]
    for i in range(n):
        title=f"{random.choice(WORDS)}Product {i+1}"
        price=round(random.uniform(10,9999),2)
        batch.append(Product(catgory=cat,title=title,description=f"Autogenerated{title}",price=price,status="active",))

        if len(batch) >= 500:
            with transaction.atomic():
                Product.objects.bulk_create(batch) 
                batch.clear()

    if batch:
        with transaction.atomic():
            Product.objects.bulk_create(batch)
    return {"created":n, "category": cat.id}


