# Generated by Django 5.2.5 on 2025-08-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='satus',
            new_name='status',
        ),
    ]
